server:
  port: 9000

eureka:
  client:
    fetch-registry: true # 테스트 입니다
    register-with-eureka: true # eureka register
    service-url:
      defaultZone: http://localhost:8761/eureka # defaultZone

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:64412
          # http://localhost:8000/user  http://localhost:64412
          predicates:
            - Path=/user/**