#server:
#  port: 9000
#
#eureka:
#  client:
#    fetch-registry: true # 테스트 입니다
#    register-with-eureka: true # eureka register
#    service-url:
#      defaultZone: http://localhost:9000/eureka # defaultZone
#
#spring:
#  application:
#    name: gateway-service
#
#  cloud:
#    gateway:
#      routes:
#        - id: auth-service
#          uri: http://localhost:64412
#          # http://localhost:8000/user  http://localhost:64412
#          predicates:
#            - Path=/user/**

server:
  port: 8761 #포트번호 지정

spring:
  application:
    name: discoveryservice # 서비스 ID

eureka:
  client:
    register-with-eureka: false # default : true
    fetch-registry: false # default : true