version: '3'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    networks:
      - msa-network

  gateway:
    image: blackbeen99/gateway
    depends_on:
      - mysql
    ports:
      - 8080:8081
    networks:
      - msa-network

  eureka:
    image: blackbeen99/eureka
    depends_on:
      - config
      - registry
      - mysql
    ports:
      - 8761:8761
    networks:
      - msa-network
    

  auth:
    image: blackbeen99/auth
    depends_on:
      - gateway
      - eureka
      - authserver
    environment:
      eureka:
        client:
          register-with-eureka: true
          fetch-registry: true
          service-url:
            defaultZone: http://localhost:8761/eureka
      mail:
        host: stmp.gmail.com
        port: 587
        properties:
          mail:
            username: "USER_NAME"
            password: "PASSWORD"
            transport:
              protocol: smtp
            smtp:
              auth: false
              timeout: 5000
              starttls.enabled: true
    ports:
      - 0:8080
    networks:
      - msa-network

networks:
  msa-network:
    external: true