server:
  port: 0

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smilegate-auth?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 9301
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  application:
    name:auth-server
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka