server:
  port: 0

sending:
  email: localhost:8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/smilegate-auth?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: root
    password: 9301
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
  application:
    name:auth-server
  redis:
    port:6379
    host:localhost
  jpa:
    properties:
      hibernate:
        dialect:
          storage_engine: innodb
    generate-ddl: true
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: localhost
      port: 6379
  jwt:
    secret-key: SECRET_KEY
    blacklist:
      access-token: BlackList_AccessToken_

  mail:
    host: stmp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: false
          timeout: 5000
          starttls.enabled: true

springdoc:
  version: v1
  swagger-ui:
    path: /swagger-ui.html
    url: /swagger-ui.html
  packages-to-scan: com.smilegate.authserver
  cache:
    disabled: true
  api-docs:
    groups:
      enabled: true


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka